---
layout: cv
title: Magnus Jr Resume
---


BYU-Idaho Student, Future Analyst, Operations Management


### Area of interests

Operations, Data Analytics, Asset/Wealth/Risk Management, and Business Intelligence 

## Education

`September 2021-December 2025`

BSc in Business Analytics at Brigham Young University - Idaho


## Scholarships

`2022-2025`

Brigham Young University - Idaho (Academic Grant) 


## Work Experiences

`April 2023 - May 2024`

Financial Accounting Teaching Assistant (Online) at Ensign College

• Graded and provided feedback for assignment, quizzes and exams for over 60 students in a timely manner 
• Organized 200+ attendance records, 50+ course materials, and 30+ announcements, improving course organization by 15% 
• Developed up to 10+ lesson plans weekly, resulting in a 20% improvement in student engagement and performance 

`July 2023 - Spetember 2023`

Summer Operations Intern at Pacific Ag

• Streamlined 2 crop harvesting operations, ensuring timely and efficient resource utilization on a daily basis 
• Enhanced up to 5 harvesting strategies through analysis on yields, weather, and soil conditions weekly 
Hermiston, Oregon 
• Learned management skills  daily, resulting in a 20% increase in team productivity and a 15% reduction in project completion time over 3 months 



`January 2022 - August 2022`

Instructor Evaluation Support Specialist at BYU-Idaho

• Reviewed Canvas online courses, and increased experience in Excel, Google sheets, Qualtrics and Power Bi 
• Evaluated instructor performance, and provided feedback for teaching enhancement on a daily basis 
• Analyzed and reported over 100+ instructor performance data for administrative decisions 



## Academic Projects

`January 2024 - April 2024`

Mutual Fund Analysis (Power BI & Tableau) at BYU-Idaho

• Analyzed mutual fund performance using Tableau and Power BI, resulting in a 22% increase in portfolio returns and a 38% 
reduction in investment risk 
• Created up to 5 interactive dashboards on Power BI for visualizing performance indicators and benchmark comparisons 
• Suggested actionable insights for informed investment decisions, contributing to a better portfolio performance by 50% 



## Key Skills 

• Data Analysis: Python, Pivot Table, and SQL 
• Business Intelligence Tools: Tableau, and Power BI 
• Microsoft Office Suite: Word, Excel and Power Point 
• Soft Skills: Teamwork, Leadership, Communication, Critical Thinking, Problem Solving, Adaptability, and Time Management


<!-- ### Footer

Last updated: May 2013 -->